Add footnote about colors being in-gamut (i.e. components in [0,1])
AcademySoftwareFoundation/OpenPBR pull request #208
Opened 2024-05-28 16:46 UTC by portsmouth

Based on the interesting discussion in https://github.com/AcademySoftwareFoundation/OpenPBR/issues/149, it seems worth adding this side note:

![image](https://github.com/AcademySoftwareFoundation/OpenPBR/assets/2774364/b3bfe9cf-7820-4dd8-bc0f-45eb21268110)

2024-05-28 18:15 UTC, portsmouth commented
@anderslanglands and @KelSolaar Would appreciate your thoughts on whether this change makes sense.

2024-06-01 23:20 UTC, KelSolaar commented
It might also be:

"... all RGB colours are in-gamut of the working space, i.e., have components in the $[0, +\inf]$ range"

- "In-gamut" of what: We need to specify the container
- Why limiting to `1]`? Colour emission should not be restricted so we might need a case for albedo et al. and another one for emission.

2024-06-04 17:24 UTC, portsmouth commented
@KelSolaar 

>It might also be: "... all RGB colours are in-gamut of the working space, i.e., have components in the $[0, \infty]$ range"

OK, so in your view "in-gamut" (of the working color space of the shader) simply means that the color components are non-negative?

>"In-gamut" of what: We need to specify the container

Can you clarify what you mean by container? We say in the spec that "A color3 value is associated with a color space ACEScg by default)" and that "The assumed color space of all the color parameters .. by default .. is assumed to be ACEScg".  

So "in-gamut" is implied to mean in-gamut of that color space (or ACEScg if unspecified). Is that still under-specified in your view?

>Why limiting to 1? Colour emission should not be restricted so we might need a case for albedo et al. and another one for emission.

Yes right, so emission color should not be restricted to [0,1], but it seemed like according to our earlier [discussion ](https://github.com/AcademySoftwareFoundation/OpenPBR/issues/149) we had agreed that for all the other colors, which represent albedos or fractional tints, they should be restricted to [0,1] (regardless of the color space). Do you still agree with that?

2024-06-04 23:18 UTC, KelSolaar commented
> OK, so in your view "in-gamut" (of the working color space of the shader) simply means that the color components are non-negative?

Yes, e.g., HDR values are considered in-gamut of their colourspace for example.

> Is that still under-specified in your view?

I would certainly be very specific, there is an infinity of gamuts and it does not cost much to add.

> Do you still agree with that?

Yes!

2024-06-04 23:24 UTC, portsmouth commented
Sorry can you clarify what you mean by “there is an infinity of gamuts”?

We say the color space must be specified (or is ACEScg by default). How can we be more specific that that?

2024-06-04 23:34 UTC, KelSolaar commented
We are splitting hairs here but "gamut" by definition (Oxford Languages) is "the complete range or scope of something", what I'm saying is that the notes does not explicitly specifies it.

> Note that we assume that all RGB colors are in the specified color space's gamut, i.e. have components in the $[0, +inf]$ range.

This is better because the "something" is specified explicitly in the sentence right next to "gamut" and you do not have to reach the end of the sentence to understand what is being said.

In theory, the *i.e.,* portion of the sentence could be omitted and the sentence would be explicit by itself, I could only write: 

> Note that we assume that all RGB colors are in-gamut.

2024-06-12 01:20 UTC, portsmouth commented
@jstone-lucasfilm Note, don't merge this one yet. There needs to be some changes to the way we describe the color ranges in the spec.

2024-09-30 20:24 UTC, portsmouth commented
I modified this as follows:

![image](https://github.com/user-attachments/assets/f188bba9-d68f-43d9-982b-48d03a110c57)

![image](https://github.com/user-attachments/assets/a4f1e4f0-911a-46a5-b47b-37f88b794ac7)

![image](https://github.com/user-attachments/assets/62bfcd3c-5b42-4424-93a6-2a96571c934e)

2024-10-15 12:44 UTC, portsmouth commented
@jstone-lucasfilm can be merged?

2025-02-21 02:32 UTC, portsmouth commented
Note we added:
>The `emission_color` however is the exception which is permitted to have arbitrarily large (positive) components, since it represents an arbitrary luminance.

But the parametrization tables were not updated to make this change, so that is still to be done.

2025-06-10 15:23 UTC, AdrienHerubel requested changes
Need a clean rebase on top of 1.1.1

2025-06-23 19:19 UTC, portsmouth commented
Can be closed, redone in https://github.com/AcademySoftwareFoundation/OpenPBR/pull/260.

2025-07-08 17:06 UTC, closed without merging