Move .html files to docs folder
AcademySoftwareFoundation/OpenPBR pull request #227
Opened 2024-07-22 20:56 UTC by portsmouth

Then GitHub pages needs to be pointed to the new `/docs` folder.

2024-08-23 17:55 UTC, virtualzavie approved these changes
LGTM

2024-08-25 00:24 UTC, portsmouth commented
(Note, on merging this, the admin needs to change the GitHub pages settings to point to the `/docs` folder.

2024-10-15 12:41 UTC, portsmouth commented
@jstone-lucasfilm can be merged? (Note that GitHub pages needs to be pointed to the new /docs folder, just after merge).

2025-06-10 15:20 UTC, AdrienHerubel requested changes
Need to fix conflicts.

2026-09-21 01:39 UTC, najibna reviewed
Moving `index.html` / `parametrization.md.html` into `docs/` is a reasonable Pages layout, but the HTML still uses repo-root `images/...` paths. Once Pages is pointed at `/docs`, those figures will 404 unless assets move with the HTML or paths become `../images/`.

This also folds in unrelated 1.1 spec edits (`emission_weight`, metal Fresnel clamp, `thin_film_ior` 1.5→1.4). Please rebase the conflicts and keep the docs move separate from the spec changes.

2026-09-22 17:39 UTC, AdrienHerubel commented
Closing for now, as the repo changed quite a bit, we can revisit once we have less branches in flight.

2026-09-22 17:39 UTC, closed without merging