Image overhaul
AcademySoftwareFoundation/OpenPBR pull request #236
Opened 2024-09-03 16:09 UTC by portsmouth

Updating images to use the new shaderball, and adding some new images.

Also indenting the anisotropy diagram to make it less distracting.

![image](https://github.com/user-attachments/assets/1783ecab-18e1-4164-a415-88541ada7f48)

2024-09-23 10:31 UTC, virtualzavie commented on index.html
> +    ![Figure [fuzz]: A checkerboard **`coat_weight`**, varying the **`coat_darkening`** over 0, 0.5, 1 (default).](dummy)
I find this particular illustration difficult to understand. The wood looks glossy everywhere, which I interpret as coated everywhere. If the intent is to show a checker of coated vs non coated parts, I'd suggest using a rough base layer.

2025-09-30 15:52 UTC, AdrienHerubel requested changes
Let's address the comment from @virtualzavie and get that change in for the fix release, we can add more updates in other PRs.

2025-12-09 15:11 UTC, AdrienHerubel commented on index.html
> +
```suggestion
```

2025-12-09 15:14 UTC, AdrienHerubel approved these changes
Let's get this first batch of improved images in. I removed the image mentioned by @virtualzavie as being hard to understand.

2025-12-09 15:14 UTC, merged